In [1]:
print(2)


2


In [ ]:
for i in 10:
    print("DOPE")

In [6]:
import numpy as np

In [7]:
print(np.array([1,2,3]))

[1 2 3]


In [9]:
print(np.array([1,2,3.0]))

[1. 2. 3.]


In [15]:
print(np.array([[1,2],, end=" ", [3,4]]))

SyntaxError: invalid syntax (<ipython-input-15-7a9fda8f9f37>, line 1)

In [23]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,6,7])



In [28]:
a==b

array([ True,  True,  True, False, False])

In [29]:
a<b

array([False, False, False,  True,  True])

In [25]:
a<=b

array([ True,  True,  True,  True,  True])

In [26]:
a>b

array([False, False, False, False, False])

In [27]:
a>=b

array([ True,  True,  True, False, False])

In [41]:
print(np.arange(30,70+1,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [33]:
for x in (a,b):
    print(x)

[1 2 3 4 5]
[1 2 3 6 7]


In [35]:
for x in range(30,70 +1):
    if(x%2==0):
        print(x)

30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70


In [36]:
import numpy as np

arr = np.array([
[
[[[1, 2, 3, 4], [5, 6, 7, 8]]
,
[[1, 2, 3, 4], [5, 6, 7, 8]]]
,
[[[1, 2, 3, 4], [5, 6, 7, 8]]
,
[[1, 2, 3, 4], [5, 6, 7, 8]]]
],
[
[[[1, 2, 3, 4], [5, 6, 7, 8]]
,
[[1, 2, 3, 4], [5, 6, 7, 8]]]
,
[[[1, 2, 3, 4], [5, 6, 7, 8]]
,
[[1, 2, 3, 4], [5, 6, 7, 8]]]
]
])

print(arr.shape)

(2, 2, 2, 2, 4)


In [49]:
a1=np.array([1,0,0])
a2=np.array([0,1,0])
a3=np.array([0,0,1])
for i in (a1,a2,a3):
    print(i)

[1 0 0]
[0 1 0]
[0 0 1]


In [77]:
arr_33=np.identity(3,dtype="int64")
print(arr_33)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [54]:
arr_55=np.identity(5,dtype="int64")
print(arr_55)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [47]:

x =  np.arange(0,8+1).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
#4. 
vec=np.arange(21)
vec[ (vec>=9) & (vec<=15) ] *= -1
print(vec)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [71]:
#5.
vec=np.diag([1,2,3,4,5])
print(vec)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [83]:
#6
vec=np.arange(9).reshape(3,3)
print(vec)
sum1=np.sum(vec)
print(sum1)
rows1=np.sum(vec,axis=1)
print(rows1)
rows2=np.sum(vec,axis=0)
print(rows2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
[ 3 12 21]
[ 9 12 15]


In [106]:
#8
aa=np.array([2,3,4,5])
ab=np.array([3,4,5,6])

ac=np.array_equal(aa,ab)

if (ac=="True"):
    print("Equal")
else:
    print("Not equal")

Not equal


In [112]:
aa=np.array([2,3,4,5])
ab=np.array([3,4,5,6])
ac=np.array([2,3,4.00001,5])

print(np.allclose(aa,ab))
print(np.allclose(aa,ac))
#allclose=calculates if aa and ac is within the accepted tolerance limit


False
True


In [113]:
#7

arr=np.array([1,2,3,4,5])
print(arr)
file=open("file.txt","w+")

file_content=str(arr)
file.write(file_content)
file.close()

file=open("file.txt","r")
file_content=file.read()

print("\n", file_content)
file.close()

[1 2 3 4 5]

 [1 2 3 4 5]


In [132]:
#9
swap=np.arange(16).reshape(4,4)
print(swap)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [131]:
swap[[0,3]]=swap[[3,0]]
print("\nAfter swapping first and last rows:\n")
print(swap)


After swapping first and last rows:

[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [133]:
swap=np.roll(swap,-1,axis=1)
print(swap)

[[ 1  2  3  0]
 [ 5  6  7  4]
 [ 9 10 11  8]
 [13 14 15 12]]


In [134]:
a=np.array([[1,2,3,4,5],[2,3,4,5,6]])
b=np.array([[1,2,3,4,5],[2,3,4,5,6]])
mul=np.multiply(a,b)
print(mul)

[[ 1  4  9 16 25]
 [ 4  9 16 25 36]]
