In [ ]:
#LAB 2

In [3]:
import numpy as np

In [9]:
R = int(input("Enter the number of rows\n"))
C = int(input("Enter the number of columns\n"))
k=C*R
print("Enter the ",k,"entries in a single line (separated by space) of first matrix\n ")
entries1 = list(map(int, input().split()))
matrix1 = np.array(entries1).reshape(R, C)
print("Enter the ",k,"entries in a single line (separated by space) of second matrix\n ")
entries2 = list(map(int, input().split()))
matrix2 = np.array(entries2).reshape(R, C)
print("Matrix 1:\n",matrix1)
print("Matrix 2:\n",matrix2)

Enter the number of rows
 2
Enter the number of columns
 2


Enter the  4 entries in a single line (separated by space) of first matrix
 


 1 2 3 4


Enter the  4 entries in a single line (separated by space) of second matrix
 


 3 4 5 6


Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[3 4]
 [5 6]]


In [10]:
dot=np.dot(matrix1,matrix2)
print("dot product of two matrix is :\n",dot)

dot product of two matrix is :
 [[13 16]
 [29 36]]


In [11]:
print("transpose of dot product is :\n",np.transpose(dot))

transpose of dot product is :
 [[13 29]
 [16 36]]


In [12]:
print("trace of dot product is :\n",np.trace(dot))

trace of dot product is :
 49


In [13]:
print("RANK of dot product is :\n",np.linalg.matrix_rank(dot))

RANK of dot product is :
 2


In [19]:
det=int(np.linalg.det(dot))
print("DETERMINANT of dot product is :\n",det)

DETERMINANT of dot product is :
 3


In [ ]:
print("Inverse of dot product is :\n",np.linalg.inv(dot))

Inverse of dot product is :
 [[ 9.   -4.  ]
 [-7.25  3.25]]


In [23]:
evalue,evect=np.linalg.eig(dot)
print("Eigenvalues of dot product is :\n",evalue)
print("Eigenvectors of dot product is :\n",evect)

Eigenvalues of dot product is :
 [ 0.08176911 48.91823089]
Eigenvectors of dot product is :
 [[-0.77805636 -0.40691011]
 [ 0.62819448 -0.91346821]]
